---
- name: Get Hard Drive Model
  hosts: all
  gather_facts: yes
  tasks:
    - name: Extract and display hard drive model
      debug:
        msg: "{{ ansible_devices | dict2items | selectattr('value.model', 'defined') | map(attribute='value.model') | list }}"
